### ISSUE TITLE
Error when running tslint-config-prettier-check

### ISSUE THREAD

**Issue by ddieppa** [alexjoverm/tslint-config-prettier#114]
I created and script in the `package.json` file with the following:
`"tslint-check": "tslint-config-prettier-check ./tslint.json"`
ran it using `yarn tslint-check` and got this error:
```console
yarn run v1.5.1
$ tslint-config-prettier-check ./tslint.json
C:\Projects\udemy\Angular 5\my-first-app\node_modules\tslint-config-prettier\lib\checker.js:18
        throw new Error("Conflict rule(s) detected in " + configFilePath + ":\n" + conflictRules.join("\n"));
        ^

Error: Conflict rule(s) detected in ./tslint.json:
eofline
import-spacing
indent
max-line-length
no-trailing-whitespace
one-line
quotemark
semicolon
typedef-whitespace
whitespace
PS C:\Projects\udemy\Angular 5\my-first-app> yarn tslint-checkyarn run v1.5.1
$ tslint-config-prettier-check ./tslint.jsonC:\Projects\udemy\Angular 5\my-first-app\node_modules\tslint-config-prettier\lib\checker.js:18        throw new Error("Conflict rule(s) detected in " + configFilePath + ":\n" + conflictRules.join("\n"));
        ^

Error: Conflict rule(s) detected in ./tslint.json:
eofline
import-spacing
indent
max-line-length
no-trailing-whitespace
one-line
quotemark
semicolon
typedef-whitespace
whitespace
    at Object.exports.check (C:\Projects\udemy\Angular 5\my-first-app\node_modules\tslint-config-prettier\lib\checker.js:18:15)    at Object.<anonymous> (C:\Projects\udemy\Angular 5\my-first-app\node_modules\tslint-config-prettier\bin\check.js:2:27)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: C:\\Windows\\system32\\cmd.exe
Arguments: /d /s /c tslint-config-prettier-check ./tslint.json
Directory: C:\\Projects\\udemy\\Angular 5\\my-first-app
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Projects\\udemy\\Angular 5\\my-first-app\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I am using VS Code with prettier extension installed, here are my devDependencies
```javascript
"devDependencies": {
    "@angular/cli": "~1.7.2",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "prettier": "^1.11.1",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "tslint-config-prettier": "^1.9.0",
    "typescript": "~2.5.3"
  }
```
Here is my tslint.js file content
```json
{
  "rulesDirectory": ["node_modules/codelyzer"],
  "rules": {
    "arrow-return-shorthand": true,
    "callable-types": true,
    "class-name": true,
    "comment-format": [true, "check-space"],
    "curly": true,
    "deprecation": {
      "severity": "warn"
    },
    "eofline": true,
    "forin": true,
    "import-blacklist": [true, "rxjs", "rxjs/Rx"],
    "import-spacing": true,
    "indent": [true, "spaces"],
    "interface-over-type-literal": true,
    "label-position": true,
    "max-line-length": [true, 140],
    "member-access": false,
    "member-ordering": [
      true,
      {
        "order": ["static-field", "instance-field", "static-method", "instance-method"]
      }
    ],
    "no-arg": true,
    "no-bitwise": true,
    "no-console": [true, "debug", "info", "time", "timeEnd", "trace"],
    "no-construct": true,
    "no-debugger": true,
    "no-duplicate-super": true,
    "no-empty": false,
    "no-empty-interface": true,
    "no-eval": true,
    "no-inferrable-types": [true, "ignore-params"],
    "no-misused-new": true,
    "no-non-null-assertion": true,
    "no-shadowed-variable": true,
    "no-string-literal": false,
    "no-string-throw": true,
    "no-switch-case-fall-through": true,
    "no-trailing-whitespace": true,
    "no-unnecessary-initializer": true,
    "no-unused-expression": true,
    "no-use-before-declare": true,
    "no-var-keyword": true,
    "object-literal-sort-keys": false,
    "one-line": [true, "check-open-brace", "check-catch", "check-else", "check-whitespace"],
    "prefer-const": true,
    "quotemark": [true, "single"],
    "radix": true,
    "semicolon": [true, "always"],
    "triple-equals": [true, "allow-null-check"],
    "typedef-whitespace": [
      true,
      {
        "call-signature": "nospace",
        "index-signature": "nospace",
        "parameter": "nospace",
        "property-declaration": "nospace",
        "variable-declaration": "nospace"
      }
    ],
    "unified-signatures": true,
    "variable-name": false,
    "whitespace": [true, "check-branch", "check-decl", "check-operator", "check-separator", "check-type"],
    "directive-selector": [true, "attribute", "app", "camelCase"],
    "component-selector": [true, "element", "app", "kebab-case"],
    "no-output-on-prefix": true,
    "use-input-property-decorator": true,
    "use-output-property-decorator": true,
    "use-host-property-decorator": true,
    "no-input-rename": true,
    "no-output-rename": true,
    "use-life-cycle-interface": true,
    "use-pipe-transform-interface": true,
    "component-class-suffix": true,
    "directive-class-suffix": true
  },
  "extends": ["tslint:latest", "tslint-config-prettier"]
}
```
This is my _User Settings_ prettier configurations:
```js
"editor.formatOnSave": true,
    "prettier.printWidth": 140,
    "prettier.singleQuote": true,
    "prettier.bracketSpacing": true,
    "prettier.semi": true,
    "prettier.useTabs": false,
    "prettier.tabWidth": 2,
```
What am I doing wrong??

**Comment by ikatyang** [comment]
Nothing wrong, that's the expected behavior, but I probably should only log conflict rules instead of just throwing them so that it won't look like a bug. 😂
